Add docs for interest work
pantheon-systems/edge-integrations-wordpress-sdk pull request #3
Opened 2022-02-02 22:31 UTC by jspellman814

These might change as we iron out [#8](https://github.com/pantheon-systems/pantheon-wordpress-edge-integrations/pull/8), so marking as draft for now.

2022-02-07 16:12 UTC, jazzsequence reviewed
A suggestion for formatting the functional docs & a general question.

Overall looks good.

2022-02-07 16:12 UTC, jazzsequence commented on docs/interest-filtering.md
> +`pantheon.ei.localized_terms`: modify terms before they are localized.
I would break these out onto separate lines and add any parameters the filter(s) use. I generally try to write docs the way they are [presented in developer.wordpress.org](https://developer.wordpress.org/reference/hooks/activate_plugin/) e.g. https://github.com/humanmade/altis-privacy/blob/master/docs/consent/filter-reference.md, so something like

```suggestion
### `pantheon.ei.localized_terms` 
Modify terms before they are localized.

#### Parameters

$terms _(array)_ The array of terms to add.
```

🔢

Question: How are terms excluded? If we're passing an array, presumably it's additive, we're able to add things to the array -- how do existing terms added by the CMS get removed from the array?

2022-02-08 16:50 UTC, jspellman814 commented on docs/interest-filtering.md
> +`pantheon.ei.localized_terms`: modify terms before they are localized.
Updated format in [76d2b5c](https://github.com/pantheon-systems/edge-integrations-wordpress-sdk/pull/3/commits/76d2b5c276285ad1b5272a735464249a403d8a94) and addressed removing term(s) from the array [1c34f23](https://github.com/pantheon-systems/edge-integrations-wordpress-sdk/pull/3/commits/1c34f237c0a6d2365459c9c1377e4bc432c9c39e).

2022-02-09 15:50 UTC, jazzsequence requested changes
A couple very minor changes but otherwise looks great!

2022-02-09 15:50 UTC, jazzsequence commented on docs/interest-filtering.md
> +function pantheon_ei_add_term( $terms ) {
I like adding strict typing to documentation. I think it helps make the examples more clear about the expected inputs and outputs. I know this is also documented in the parameters, but it reinforces that and also establishes best practices. 🔢

```suggestion
function pantheon_ei_add_term( array $terms ) : array {
```

2022-02-09 15:50 UTC, jazzsequence commented on docs/interest-filtering.md
> +```bash
All of these code snippets are PHP, so the language after the backticks should be PHP for proper code styles (not sure how/if this applies to the official documentation). 🔢

```suggestion
```php
```

2022-02-10 16:46 UTC, jazzsequence approved these changes
🚀

2022-02-10 16:46 UTC, merged